import React, { useState, useEffect } from 'react';
import { LanguageContext } from './LanguageContext.js';

// Translation data
const translations = {
  en: {
    heroTitle: 'HealthWell',
    heroSubtitle: ['Intelligent', 'Personalized', 'Advanced', 'Comprehensive', 'Smart'],
    aiHealthAnalysis: 'AI-Powered Health Analysis',
    uploadDescription: 'Upload medical documents and get instant AI insights',
    uploadMedicalRecords: 'Upload Medical Records',
    analysisCompleted: 'Analysis Completed',
    analyzing: 'Analyzing...',
    analyzeHealthData: 'Analyze Health Data',
    analyzingDocument: 'Analyzing your medical document with AI...',
    analysisSuccessful: 'Analysis Successful! Preparing your personalized report...',
    intelligentAssistant: 'Intelligent Health Assistant',
    instantAnswers: 'Get instant answers to your health questions from our AI',
    listening: 'Listening...',
    askHealthQuestion: 'Ask me anything about health...',
    asking: 'Asking...',
    askHealthWellAI: 'Ask HealthWell AI',
    iotHealthMonitoring: 'IoT Health Monitoring',
    futurePerk: 'Future Perk',
    iotSubtitle: 'Connect your devices or input data manually for comprehensive health analysis',
    comingSoonFeature: 'This feature is coming soon! Experience the future of personalized health monitoring.',
    manualInput: 'Manual Input',
    iotDevices: 'IoT Devices',
    heartRate: 'Heart Rate',
    enterBPM: 'Enter BPM',
    bloodPressure: 'Blood Pressure',
    systolic: 'Systolic',
    diastolic: 'Diastolic',
    temperature: 'Temperature',
    enterTemp: 'Enter temp',
    oxygenLevel: 'Oxygen Level',
    enterPercent: 'Enter %',
    weight: 'Weight',
    enterWeight: 'Enter weight',
    dailySteps: 'Daily Steps',
    enterSteps: 'Enter steps',
    availableHealthDevices: 'Available Health Devices',
    scanning: 'Scanning...',
    scanForDevices: 'Scan for Devices',
    disconnect: 'Disconnect',
    connect: 'Connect',
    generateHealthReport: 'Generate Health Report',
    healthAnalysisReport: 'Your Health Analysis Report',
    generatedOn: 'Generated on',
    healthMetricsSummary: 'Health Metrics Summary',
    sending: 'Sending...',
    send: 'Send',
    advancedHealthcareAnalytics: 'Advanced Healthcare Analytics',
    platform: 'Platform',
    documentAnalysis: 'Document Analysis',
    iotIntegration: 'IoT Integration',
    aiDiagnostics: 'AI Diagnostics',
    resources: 'Resources',
    documentation: 'Documentation',
    apiReference: 'API Reference',
    support: 'Support',
    advancedHealthcareTechnology: 'Advanced Healthcare Technology',
    hipaaCompliant: 'HIPAA Compliant',
    iso27001: 'ISO 27001',
    fdaApproved: 'FDA Approved',
    signIn: 'Sign In',
    getStarted: 'Get Started',
    copyReport: 'Copy Report',
    downloadReport: 'Download Report',
    closeReport: 'Close Report',
    
    // Legacy keys for backward compatibility
    uploadDocument: 'Upload Medical Document',
    dragDropText: 'Drag & drop your medical documents here',
    orText: 'or',
    browseFiles: 'browse files',
    supportedFormats: 'Supported formats: PDF, JPG, PNG, DOCX',
    analysisComplete: 'Analysis Complete!',
    viewReport: 'View Report',
    askQuestion: 'Ask me anything about health...',
    iotTitle: 'IoT Health Monitoring',
    scanDevices: 'Scan for Devices',
    connectDevice: 'Connect Device',
    connected: 'Connected',
    generateReport: 'Generate Health Report',
    chatTitle: 'Health Assistant',
    reportTab: 'Report',
    chatTab: 'Chat',
    footerBrand: 'HealthWell',
    footerTagline: 'Advanced Healthcare Analytics',
    platformTitle: 'Platform',
    resourcesTitle: 'Resources',
    copyright: '© 2024 HealthWell. Advanced Healthcare Technology.',
    home: 'Home',
     about: 'About'
   },
  hi: {
    heroTitle: 'हेल्थवेल',
    heroSubtitle: ['बुद्धिमान', 'व्यक्तिगत', 'उन्नत', 'व्यापक', 'स्मार्ट'],
    aiHealthAnalysis: 'एआई-संचालित स्वास्थ्य विश्लेषण',
    uploadDescription: 'चिकित्सा दस्तावेज अपलोड करें और तत्काल एआई अंतर्दृष्टि प्राप्त करें',
    uploadMedicalRecords: 'चिकित्सा रिकॉर्ड अपलोड करें',
    analysisCompleted: 'विश्लेषण पूर्ण',
    analyzing: 'विश्लेषण कर रहे हैं...',
    analyzeHealthData: 'स्वास्थ्य डेटा का विश्लेषण करें',
    analyzingDocument: 'एआई के साथ आपके चिकित्सा दस्तावेज का विश्लेषण कर रहे हैं...',
    analysisSuccessful: 'विश्लेषण सफल! आपकी व्यक्तिगत रिपोर्ट तैयार कर रहे हैं...',
    intelligentAssistant: 'बुद्धिमान स्वास्थ्य सहायक',
    instantAnswers: 'हमारे एआई से अपने स्वास्थ्य प्रश्नों के तत्काल उत्तर प्राप्त करें',
    listening: 'सुन रहे हैं...',
    askHealthQuestion: 'स्वास्थ्य के बारे में कुछ भी पूछें...',
    asking: 'पूछ रहे हैं...',
    askHealthWellAI: 'हेल्थवेल एआई से पूछें',
    iotHealthMonitoring: 'IoT स्वास्थ्य निगरानी',
    futurePerk: 'भविष्य का लाभ',
    iotSubtitle: 'व्यापक स्वास्थ्य विश्लेषण के लिए अपने उपकरणों को कनेक्ट करें या मैन्युअल रूप से डेटा इनपुट करें',
    comingSoonFeature: 'यह सुविधा जल्द आ रही है! व्यक्तिगत स्वास्थ्य निगरानी के भविष्य का अनुभव करें।',
    manualInput: 'मैन्युअल इनपुट',
    iotDevices: 'IoT उपकरण',
    heartRate: 'हृदय गति',
    enterBPM: 'BPM दर्ज करें',
    bloodPressure: 'रक्तचाप',
    systolic: 'सिस्टोलिक',
    diastolic: 'डायस्टोलिक',
    temperature: 'तापमान',
    enterTemp: 'तापमान दर्ज करें',
    oxygenLevel: 'ऑक्सीजन स्तर',
    enterPercent: '% दर्ज करें',
    weight: 'वजन',
    enterWeight: 'वजन दर्ज करें',
    dailySteps: 'दैनिक कदम',
    enterSteps: 'कदम दर्ज करें',
    availableHealthDevices: 'उपलब्ध स्वास्थ्य उपकरण',
    scanning: 'स्कैन कर रहे हैं...',
    scanForDevices: 'उपकरणों के लिए स्कैन करें',
    disconnect: 'डिस्कनेक्ट करें',
    connect: 'कनेक्ट करें',
    generateHealthReport: 'स्वास्थ्य रिपोर्ट जेनरेट करें',
    healthAnalysisReport: 'आपकी स्वास्थ्य विश्लेषण रिपोर्ट',
    generatedOn: 'पर जेनरेट किया गया',
    healthMetricsSummary: 'स्वास्थ्य मेट्रिक्स सारांश',
    sending: 'भेज रहे हैं...',
    send: 'भेजें',
    advancedHealthcareAnalytics: 'उन्नत स्वास्थ्य सेवा विश्लेषण',
    platform: 'प्लेटफॉर्म',
    documentAnalysis: 'दस्तावेज विश्लेषण',
    iotIntegration: 'IoT एकीकरण',
    aiDiagnostics: 'एआई निदान',
    resources: 'संसाधन',
    documentation: 'प्रलेखन',
    apiReference: 'API संदर्भ',
    support: 'सहायता',
    advancedHealthcareTechnology: 'उन्नत स्वास्थ्य सेवा प्रौद्योगिकी',
    hipaaCompliant: 'HIPAA अनुपालित',
    iso27001: 'ISO 27001',
    fdaApproved: 'FDA अनुमोदित',
    signIn: 'साइन इन',
    getStarted: 'शुरू करें',
    copyReport: 'रिपोर्ट कॉपी करें',
    downloadReport: 'रिपोर्ट डाउनलोड करें',
    closeReport: 'रिपोर्ट बंद करें',
    
    // Legacy keys for backward compatibility
    uploadDocument: 'मेडिकल दस्तावेज़ अपलोड करें',
    dragDropText: 'अपने मेडिकल दस्तावेज़ यहाँ खींचें और छोड़ें',
    orText: 'या',
    browseFiles: 'फाइलें ब्राउज़ करें',
    supportedFormats: 'समर्थित प्रारूप: PDF, JPG, PNG, DOCX',
    analysisComplete: 'विश्लेषण पूर्ण!',
    viewReport: 'रिपोर्ट देखें',
    askQuestion: 'स्वास्थ्य के बारे में कुछ भी पूछें...',
    iotTitle: 'IoT स्वास्थ्य निगरानी',
    scanDevices: 'उपकरण स्कैन करें',
    connectDevice: 'उपकरण कनेक्ट करें',
    connected: 'कनेक्टेड',
    generateReport: 'स्वास्थ्य रिपोर्ट जेनरेट करें',
    chatTitle: 'स्वास्थ्य सहायक',
    reportTab: 'रिपोर्ट',
    chatTab: 'चैट',
    footerBrand: 'हेल्थवेल',
    footerTagline: 'उन्नत स्वास्थ्य सेवा विश्लेषण',
    platformTitle: 'प्लेटफॉर्म',
    resourcesTitle: 'संसाधन',
    copyright: '© 2024 हेल्थवेल। उन्नत स्वास्थ्य सेवा प्रौद्योगिकी।',
    home: 'होम',
     about: 'के बारे में'
   },
  bn: {
    heroTitle: 'হেলথওয়েল',
    heroSubtitle: ['বুদ্ধিমান', 'ব্যক্তিগত', 'উন্নত', 'ব্যাপক', 'স্মার্ট'],
    aiHealthAnalysis: 'এআই-চালিত স্বাস্থ্য বিশ্লেষণ',
    uploadDescription: 'চিকিৎসা নথি আপলোড করুন এবং তাৎক্ষণিক এআই অন্তর্দৃষ্টি পান',
    uploadMedicalRecords: 'চিকিৎসা রেকর্ড আপলোড করুন',
    analysisCompleted: 'বিশ্লেষণ সম্পূর্ণ',
    analyzing: 'বিশ্লেষণ করছি...',
    analyzeHealthData: 'স্বাস্থ্য ডেটা বিশ্লেষণ করুন',
    analyzingDocument: 'এআই দিয়ে আপনার চিকিৎসা নথি বিশ্লেষণ করছি...',
    analysisSuccessful: 'বিশ্লেষণ সফল! আপনার ব্যক্তিগত রিপোর্ট প্রস্তুত করছি...',
    intelligentAssistant: 'বুদ্ধিমান স্বাস্থ্য সহায়ক',
    instantAnswers: 'আমাদের এআই থেকে আপনার স্বাস্থ্য প্রশ্নের তাৎক্ষণিক উত্তর পান',
    listening: 'শুনছি...',
    askHealthQuestion: 'স্বাস্থ্য সম্পর্কে যেকোনো কিছু জিজ্ঞাসা করুন...',
    asking: 'জিজ্ঞাসা করছি...',
    askHealthWellAI: 'হেলথওয়েল এআইকে জিজ্ঞাসা করুন',
    iotHealthMonitoring: 'IoT স্বাস্থ্য পর্যবেক্ষণ',
    futurePerk: 'ভবিষ্যতের সুবিধা',
    iotSubtitle: 'ব্যাপক স্বাস্থ্য বিশ্লেষণের জন্য আপনার ডিভাইসগুলি সংযুক্ত করুন বা ম্যানুয়ালি ডেটা ইনপুট করুন',
    comingSoonFeature: 'এই বৈশিষ্ট্যটি শীঘ্রই আসছে! ব্যক্তিগত স্বাস্থ্য পর্যবেক্ষণের ভবিষ্যত অনুভব করুন।',
    manualInput: 'ম্যানুয়াল ইনপুট',
    iotDevices: 'IoT ডিভাইস',
    heartRate: 'হৃদস্পন্দন',
    enterBPM: 'BPM প্রবেশ করুন',
    bloodPressure: 'রক্তচাপ',
    systolic: 'সিস্টোলিক',
    diastolic: 'ডায়াস্টোলিক',
    temperature: 'তাপমাত্রা',
    enterTemp: 'তাপমাত্রা প্রবেশ করুন',
    oxygenLevel: 'অক্সিজেনের মাত্রা',
    enterPercent: '% প্রবেশ করুন',
    weight: 'ওজন',
    enterWeight: 'ওজন প্রবেশ করুন',
    dailySteps: 'দৈনিক পদক্ষেপ',
    enterSteps: 'পদক্ষেপ প্রবেশ করুন',
    availableHealthDevices: 'উপলব্ধ স্বাস্থ্য ডিভাইস',
    scanning: 'স্ক্যান করছি...',
    scanForDevices: 'ডিভাইসের জন্য স্ক্যান করুন',
    disconnect: 'সংযোগ বিচ্ছিন্ন করুন',
    connect: 'সংযুক্ত করুন',
    generateHealthReport: 'স্বাস্থ্য রিপোর্ট তৈরি করুন',
    healthAnalysisReport: 'আপনার স্বাস্থ্য বিশ্লেষণ রিপোর্ট',
    generatedOn: 'তৈরি হয়েছে',
    healthMetricsSummary: 'স্বাস্থ্য মেট্রিক্স সারসংক্ষেপ',
    sending: 'পাঠাচ্ছি...',
    send: 'পাঠান',
    advancedHealthcareAnalytics: 'উন্নত স্বাস্থ্যসেবা বিশ্লেষণ',
    platform: 'প্ল্যাটফর্ম',
    documentAnalysis: 'নথি বিশ্লেষণ',
    iotIntegration: 'IoT একীকরণ',
    aiDiagnostics: 'এআই নির্ণয়',
    resources: 'সম্পদ',
    documentation: 'ডকুমেন্টেশন',
    apiReference: 'API রেফারেন্স',
    support: 'সহায়তা',
    advancedHealthcareTechnology: 'উন্নত স্বাস্থ্যসেবা প্রযুক্তি',
    hipaaCompliant: 'HIPAA সম্মত',
    iso27001: 'ISO 27001',
    fdaApproved: 'FDA অনুমোদিত',
    signIn: 'সাইন ইন',
    getStarted: 'শুরু করুন',
    copyReport: 'রিপোর্ট কপি করুন',
    downloadReport: 'রিপোর্ট ডাউনলোড করুন',
    closeReport: 'রিপোর্ট বন্ধ করুন',
    
    // Legacy keys for backward compatibility
    uploadDocument: 'মেডিকেল ডকুমেন্ট আপলোড করুন',
    dragDropText: 'আপনার মেডিকেল ডকুমেন্ট এখানে টেনে আনুন',
    orText: 'অথবা',
    browseFiles: 'ফাইল ব্রাউজ করুন',
    supportedFormats: 'সমর্থিত ফরম্যাট: PDF, JPG, PNG, DOCX',
    analysisComplete: 'বিশ্লেষণ সম্পূর্ণ!',
    viewReport: 'রিপোর্ট দেখুন',
    askQuestion: 'স্বাস্থ্য সম্পর্কে যেকোনো প্রশ্ন করুন...',
    iotTitle: 'IoT স্বাস্থ্য পর্যবেক্ষণ',
    scanDevices: 'ডিভাইস স্ক্যান করুন',
    connectDevice: 'ডিভাইস সংযুক্ত করুন',
    connected: 'সংযুক্ত',
    generateReport: 'স্বাস্থ্য রিপোর্ট তৈরি করুন',
    chatTitle: 'স্বাস্থ্য সহায়ক',
    reportTab: 'রিপোর্ট',
    chatTab: 'চ্যাট',
    footerBrand: 'হেলথওয়েল',
    footerTagline: 'উন্নত স্বাস্থ্যসেবা বিশ্লেষণ',
    platformTitle: 'প্ল্যাটফর্ম',
    resourcesTitle: 'সম্পদ',
    copyright: '© ২০২৪ হেলথওয়েল। উন্নত স্বাস্থ্যসেবা প্রযুক্তি।',
    home: 'হোম',
     about: 'সম্পর্কে'
   },
  te: {
    heroTitle: 'హెల్త్‌వెల్',
    heroSubtitle: ['తెలివైన', 'వ్యక్తిగత', 'అధునాతన', 'సమగ్ర', 'స్మార్ట్'],
    aiHealthAnalysis: 'AI-శక్తితో ఆరోగ్య విశ్లేషణ',
    uploadDescription: 'వైద్య పత్రాలను అప్‌లోడ్ చేసి తక్షణ AI అంతర్దృష్టులను పొందండి',
    uploadMedicalRecords: 'వైద్య రికార్డులను అప్‌లోడ్ చేయండి',
    analysisCompleted: 'విశ్లేషణ పూర్తయింది',
    analyzing: 'విశ్లేషిస్తున్నాం...',
    analyzeHealthData: 'ఆరోగ్య డేటాను విశ్లేషించండి',
    analyzingDocument: 'AI తో మీ వైద్య పత్రాన్ని విశ్లేషిస్తున్నాం...',
    analysisSuccessful: 'విశ్లేషణ విజయవంతం! మీ వ్యక్తిగత నివేదికను తయారు చేస్తున్నాం...',
    intelligentAssistant: 'తెలివైన ఆరోగ్య సహాయకుడు',
    instantAnswers: 'మా AI నుండి మీ ఆరోగ్య ప్రశ్నలకు తక్షణ సమాధానాలు పొందండి',
    listening: 'వింటున్నాం...',
    askHealthQuestion: 'ఆరోగ్యం గురించి ఏదైనా అడగండి...',
    asking: 'అడుగుతున్నాం...',
    askHealthWellAI: 'హెల్త్‌వెల్ AIని అడగండి',
    iotHealthMonitoring: 'IoT ఆరోగ్య పర్యవేక్షణ',
    futurePerk: 'భవిష్యత్ ప్రయోజనం',
    iotSubtitle: 'సమగ్ర ఆరోగ్య విశ్లేషణ కోసం మీ పరికరాలను కనెక్ట్ చేయండి లేదా మాన్యువల్‌గా డేటాను ఇన్‌పుట్ చేయండి',
    comingSoonFeature: 'ఈ ఫీచర్ త్వరలో వస్తుంది! వ్యక్తిగత ఆరోగ్య పర్యవేక్షణ భవిష్యత్తును అనుభవించండి।',
    manualInput: 'మాన్యువల్ ఇన్‌పుట్',
    iotDevices: 'IoT పరికరాలు',
    heartRate: 'హృదయ స్పందన',
    enterBPM: 'BPM నమోదు చేయండి',
    bloodPressure: 'రక్తపోటు',
    systolic: 'సిస్టోలిక్',
    diastolic: 'డయాస్టోలిక్',
    temperature: 'ఉష్ణోగ్రత',
    enterTemp: 'ఉష్ణోగ్రత నమోదు చేయండి',
    oxygenLevel: 'ఆక్సిజన్ స్థాయి',
    enterPercent: '% నమోదు చేయండి',
    weight: 'బరువు',
    enterWeight: 'బరువు నమోదు చేయండి',
    dailySteps: 'రోజువారీ అడుగులు',
    enterSteps: 'అడుగులు నమోదు చేయండి',
    availableHealthDevices: 'అందుబాటులో ఉన్న ఆరోగ్య పరికరాలు',
    scanning: 'స్కాన్ చేస్తున్నాం...',
    scanForDevices: 'పరికరాల కోసం స్కాన్ చేయండి',
    disconnect: 'డిస్‌కనెక్ట్ చేయండి',
    connect: 'కనెక్ట్ చేయండి',
    generateHealthReport: 'ఆరోగ్య నివేదిక రూపొందించండి',
    healthAnalysisReport: 'మీ ఆరోగ్య విశ్లేషణ నివేదిక',
    generatedOn: 'రూపొందించబడింది',
    healthMetricsSummary: 'ఆరోగ్య మెట్రిక్స్ సారాంశం',
    sending: 'పంపుతున్నాం...',
    send: 'పంపండి',
    advancedHealthcareAnalytics: 'అధునాతన ఆరోగ్య సంరక్షణ విశ్లేషణలు',
    platform: 'ప్లాట్‌ఫారమ్',
    documentAnalysis: 'పత్రం విశ్లేషణ',
    iotIntegration: 'IoT ఏకీకరణ',
    aiDiagnostics: 'AI నిర్ధారణలు',
    resources: 'వనరులు',
    documentation: 'డాక్యుమెంటేషన్',
    apiReference: 'API రిఫరెన్స్',
    support: 'మద్దతు',
    advancedHealthcareTechnology: 'అధునాతన ఆరోగ్య సంరక్షణ సాంకేతికత',
    hipaaCompliant: 'HIPAA అనుకూలం',
    iso27001: 'ISO 27001',
    fdaApproved: 'FDA ఆమోదించబడింది',
    signIn: 'సైన్ ఇన్',
    getStarted: 'ప్రారంభించండి',
    copyReport: 'నివేదికను కాపీ చేయండి',
    downloadReport: 'నివేదికను డౌన్‌లోడ్ చేయండి',
    closeReport: 'నివేదికను మూసివేయండి',
    uploadDocument: 'వైద్య పత్రాన్ని అప్‌లోడ్ చేయండి',
    dragDropText: 'మీ వైద్య పత్రాలను ఇక్కడ లాగి వదలండి',
    orText: 'లేదా',
    browseFiles: 'ఫైల్‌లను బ్రౌజ్ చేయండి',
    supportedFormats: 'మద్దతు ఇచ్చే ఫార్మాట్‌లు: PDF, JPG, PNG, DOCX',
    analysisComplete: 'విశ్లేషణ పూర్తయింది!',
    viewReport: 'నివేదికను చూడండి',
    askQuestion: 'ఆరోగ్యం గురించి ఏదైనా అడగండి...',
    iotTitle: 'IoT ఆరోగ్య పర్యవేక్షణ',
    scanDevices: 'పరికరాలను స్కాన్ చేయండి',
    connectDevice: 'పరికరాన్ని కనెక్ట్ చేయండి',
    connected: 'కనెక్ట్ చేయబడింది',
    generateReport: 'ఆరోగ్య నివేదిక రూపొందించండి',
    chatTitle: 'ఆరోగ్య సహాయకుడు',
    reportTab: 'నివేదిక',
    chatTab: 'చాట్',
    footerBrand: 'హెల్త్‌వెల్',
    footerTagline: 'అధునాతన ఆరోగ్య సంరక్షణ విశ్లేషణలు',
    platformTitle: 'ప్లాట్‌ఫారమ్',
    resourcesTitle: 'వనరులు',
    copyright: '© 2024 హెల్త్‌వెల్। అధునాతన ఆరోగ్య సంరక్షణ సాంకేతికత।',
    home: 'హోమ్',
    about: 'గురించి'
  },
  mr: {
    heroTitle: 'हेल्थवेल',
    heroSubtitle: ['बुद्धिमान', 'वैयक्तिक', 'प्रगत', 'सर्वसमावेशक', 'स्मार्ट'],
    aiHealthAnalysis: 'AI-चालित आरोग्य विश्लेषण',
    uploadDescription: 'वैद्यकीय कागदपत्रे अपलोड करा आणि तत्काळ AI अंतर्दृष्टी मिळवा',
    uploadMedicalRecords: 'वैद्यकीय नोंदी अपलोड करा',
    analysisCompleted: 'विश्लेषण पूर्ण',
    analyzing: 'विश्लेषण करत आहे...',
    analyzeHealthData: 'आरोग्य डेटाचे विश्लेषण करा',
    analyzingDocument: 'AI सह तुमच्या वैद्यकीय कागदपत्राचे विश्लेषण करत आहे...',
    analysisSuccessful: 'विश्लेषण यशस्वी! तुमचा वैयक्तिक अहवाल तयार करत आहे...',
    intelligentAssistant: 'बुद्धिमान आरोग्य सहाय्यक',
    instantAnswers: 'आमच्या AI कडून तुमच्या आरोग्य प्रश्नांची तत्काळ उत्तरे मिळवा',
    listening: 'ऐकत आहे...',
    askHealthQuestion: 'आरोग्याबद्दल काहीही विचारा...',
    asking: 'विचारत आहे...',
    askHealthWellAI: 'हेल्थवेल AI ला विचारा',
    iotHealthMonitoring: 'IoT आरोग्य निरीक्षण',
    futurePerk: 'भविष्यातील फायदा',
    iotSubtitle: 'सर्वसमावेशक आरोग्य विश्लेषणासाठी तुमची उपकरणे कनेक्ट करा किंवा मॅन्युअली डेटा इनपुट करा',
    comingSoonFeature: 'हे वैशिष्ट्य लवकरच येत आहे! वैयक्तिक आरोग्य निरीक्षणाच्या भविष्याचा अनुभव घ्या।',
    manualInput: 'मॅन्युअल इनपुट',
    iotDevices: 'IoT उपकरणे',
    heartRate: 'हृदयाची गती',
    enterBPM: 'BPM प्रविष्ट करा',
    bloodPressure: 'रक्तदाब',
    systolic: 'सिस्टोलिक',
    diastolic: 'डायस्टोलिक',
    temperature: 'तापमान',
    enterTemp: 'तापमान प्रविष्ट करा',
    oxygenLevel: 'ऑक्सिजन पातळी',
    enterPercent: '% प्रविष्ट करा',
    weight: 'वजन',
    enterWeight: 'वजन प्रविष्ट करा',
    dailySteps: 'दैनंदिन पावले',
    enterSteps: 'पावले प्रविष्ट करा',
    availableHealthDevices: 'उपलब्ध आरोग्य उपकरणे',
    scanning: 'स्कॅन करत आहे...',
    scanForDevices: 'उपकरणांसाठी स्कॅन करा',
    disconnect: 'डिस्कनेक्ट करा',
    connect: 'कनेक्ट करा',
    generateHealthReport: 'आरोग्य अहवाल तयार करा',
    healthAnalysisReport: 'तुमचा आरोग्य विश्लेषण अहवाल',
    generatedOn: 'तयार केले',
    healthMetricsSummary: 'आरोग्य मेट्रिक्स सारांश',
    sending: 'पाठवत आहे...',
    send: 'पाठवा',
    advancedHealthcareAnalytics: 'प्रगत आरोग्यसेवा विश्लेषणे',
    platform: 'प्लॅटफॉर्म',
    documentAnalysis: 'कागदपत्र विश्लेषण',
    iotIntegration: 'IoT एकीकरण',
    aiDiagnostics: 'AI निदान',
    resources: 'संसाधने',
    documentation: 'दस्तऐवजीकरण',
    apiReference: 'API संदर्भ',
    support: 'समर्थन',
    advancedHealthcareTechnology: 'प्रगत आरोग्यसेवा तंत्रज्ञान',
    hipaaCompliant: 'HIPAA अनुपालित',
    iso27001: 'ISO 27001',
    fdaApproved: 'FDA मंजूर',
    signIn: 'साइन इन',
    getStarted: 'सुरुवात करा',
    copyReport: 'अहवाल कॉपी करा',
    downloadReport: 'अहवाल डाउनलोड करा',
    closeReport: 'अहवाल बंद करा',
    uploadDocument: 'वैद्यकीय कागदपत्र अपलोड करा',
    dragDropText: 'तुमची वैद्यकीय कागदपत्रे येथे ड्रॅग आणि ड्रॉप करा',
    orText: 'किंवा',
    browseFiles: 'फाइल्स ब्राउझ करा',
    supportedFormats: 'समर्थित स्वरूप: PDF, JPG, PNG, DOCX',
    analysisComplete: 'विश्लेषण पूर्ण!',
    viewReport: 'अहवाल पहा',
    askQuestion: 'आरोग्याबद्दल काहीही विचारा...',
    iotTitle: 'IoT आरोग्य निरीक्षण',
    scanDevices: 'उपकरणे स्कॅन करा',
    connectDevice: 'उपकरण कनेक्ट करा',
    connected: 'कनेक्ट केले',
    generateReport: 'आरोग्य अहवाल तयार करा',
    chatTitle: 'आरोग्य सहाय्यक',
    reportTab: 'अहवाल',
    chatTab: 'चॅट',
    footerBrand: 'हेल्थवेल',
    footerTagline: 'प्रगत आरोग्यसेवा विश्लेषणे',
    platformTitle: 'प्लॅटफॉर्म',
    resourcesTitle: 'संसाधने',
    copyright: '© 2024 हेल्थवेल। प्रगत आरोग्यसेवा तंत्रज्ञान।',
    home: 'होम',
     about: 'बद्दल'
   },
  ta: {
    heroTitle: 'ஹெல்த்வெல்',
    heroSubtitle: ['புத்திசாலி', 'தனிப்பட்ட', 'மேம்பட்ட', 'விரிவான', 'ஸ்மார்ட்'],
    aiHealthAnalysis: 'AI-இயங்கும் சுகாதார பகுப்பாய்வு',
    uploadDescription: 'மருத்துவ ஆவணங்களை பதிவேற்றி உடனடி AI நுண்ணறிவுகளைப் பெறுங்கள்',
    uploadMedicalRecords: 'மருத்துவ பதிவுகளை பதிவேற்றவும்',
    analysisCompleted: 'பகுப்பாய்வு முடிந்தது',
    analyzing: 'பகுப்பாய்வு செய்கிறோம்...',
    analyzeHealthData: 'சுகாதார தரவை பகுப்பாய்வு செய்யுங்கள்',
    analyzingDocument: 'AI உடன் உங்கள் மருத்துவ ஆவணத்தை பகுப்பாய்வு செய்கிறோம்...',
    analysisSuccessful: 'பகுப்பாய்வு வெற்றிகரமாக! உங்கள் தனிப்பட்ட அறிக்கையை தயாரிக்கிறோம்...',
    intelligentAssistant: 'புத்திசாலி சுகாதார உதவியாளர்',
    instantAnswers: 'எங்கள் AI இலிருந்து உங்கள் சுகாதார கேள்விகளுக்கு உடனடி பதில்களைப் பெறுங்கள்',
    listening: 'கேட்கிறோம்...',
    askHealthQuestion: 'சுகாதாரத்தைப் பற்றி எதையும் கேளுங்கள்...',
    asking: 'கேட்கிறோம்...',
    askHealthWellAI: 'ஹெல்த்வெல் AI ஐ கேளுங்கள்',
    iotHealthMonitoring: 'IoT சுகாதார கண்காணிப்பு',
    futurePerk: 'எதிர்கால நன்மை',
    iotSubtitle: 'விரிவான சுகாதார பகுப்பாய்வுக்காக உங்கள் சாधனங்களை இணைக்கவும் அல்லது கைமுறையாக தரவை உள்ளிடவும்',
    comingSoonFeature: 'இந்த அம்சம் விரைவில் வருகிறது! தனிப்பட்ட சுகாதார கண்காணிப்பின் எதிர்காலத்தை அனுபவிக்கவும்।',
    manualInput: 'கைமுறை உள்ளீடு',
    iotDevices: 'IoT சாधனங்கள்',
    heartRate: 'இதய துடிப்பு',
    enterBPM: 'BPM உள்ளிடவும்',
    bloodPressure: 'இரத்த அழுத்தம்',
    systolic: 'சிஸ்டோலிக்',
    diastolic: 'டயாஸ்டோலிக்',
    temperature: 'வெப்பநிலை',
    enterTemp: 'வெப்பநிலை உள்ளிடவும்',
    oxygenLevel: 'ஆக்ஸிஜன் அளவு',
    enterPercent: '% உள்ளிடவும்',
    weight: 'எடை',
    enterWeight: 'எடை உள்ளிடவும்',
    dailySteps: 'தினசரி படிகள்',
    enterSteps: 'படிகள் உள்ளிடவும்',
    availableHealthDevices: 'கிடைக்கும் சுகாதார சாधனங்கள்',
    scanning: 'ஸ்கேன் செய்கிறோம்...',
    scanForDevices: 'சாधனங்களுக்கு ஸ்கேன் செய்யுங்கள்',
    disconnect: 'துண்டிக்கவும்',
    connect: 'இணைக்கவும்',
    generateHealthReport: 'சுகாதார அறிக்கையை உருவாக்கவும்',
    healthAnalysisReport: 'உங்கள் சுகாதார பகுப்பாய்வு அறிக்கை',
    generatedOn: 'உருவாக்கப்பட்டது',
    healthMetricsSummary: 'சுகாதார அளவீடுகள் சுருக்கம்',
    sending: 'அனுப்புகிறோம்...',
    send: 'அனுப்பவும்',
    advancedHealthcareAnalytics: 'மேம்பட்ட சுகாதார பகுப்பாய்வுகள்',
    platform: 'தளம்',
    documentAnalysis: 'ஆவண பகுப்பாய்வு',
    iotIntegration: 'IoT ஒருங்கிணைப்பு',
    aiDiagnostics: 'AI நோயறிதல்',
    resources: 'வளங்கள்',
    documentation: 'ஆவணப்படுத்தல்',
    apiReference: 'API குறிப்பு',
    support: 'ஆதரவு',
    advancedHealthcareTechnology: 'மேம்பட்ட சுகாதார தொழில்நுட்பம்',
    hipaaCompliant: 'HIPAA இணக்கமான',
    iso27001: 'ISO 27001',
    fdaApproved: 'FDA அங்கீகரிக்கப்பட்டது',
    signIn: 'உள்நுழைக',
    getStarted: 'தொடங்குங்கள்',
    copyReport: 'அறிக்கையை நகலெடுக்கவும்',
    downloadReport: 'அறிக்கையை பதிவிறக்கவும்',
    closeReport: 'அறிக்கையை மூடவும்',
    uploadDocument: 'மருத்துவ ஆவணத்தை பதிவேற்றவும்',
    dragDropText: 'உங்கள் மருத்துவ ஆவணங்களை இங்கே இழுத்து விடவும்',
    orText: 'அல்லது',
    browseFiles: 'கோப்புகளை உலாவவும்',
    supportedFormats: 'ஆதரிக்கப்படும் வடிவங்கள்: PDF, JPG, PNG, DOCX',
    analysisComplete: 'பகுப்பாய்வு முடிந்தது!',
    viewReport: 'அறிக்கையைப் பார்க்கவும்',
    askQuestion: 'சுகாதாரத்தைப் பற்றி எதையும் கேளுங்கள்...',
    iotTitle: 'IoT சுகாதார கண்காணிப்பு',
    scanDevices: 'சாधனங்களை ஸ்கேன் செய்யுங்கள்',
    connectDevice: 'சாधனத்தை இணைக்கவும்',
    connected: 'இணைக்கப்பட்டது',
    generateReport: 'சுகாதார அறிக்கையை உருவாக்கவும்',
    chatTitle: 'சுகாதார உதவியாளர்',
    reportTab: 'அறிக்கை',
    chatTab: 'அரட்டை',
    footerBrand: 'ஹெல்த்வெல்',
    footerTagline: 'மேம்பட்ட சுகாதார பகுப்பாய்வுகள்',
    platformTitle: 'தளம்',
    resourcesTitle: 'வளங்கள்',
    copyright: '© 2024 ஹெல்த்வெல்। மேம்பட்ட சுகாதார தொழில்நுட்பம்।',
    home: 'முகப்பு',
    about: 'பற்றி'
  },
  gu: {
    heroTitle: 'હેલ્થવેલ',
    heroSubtitle: ['બુદ્ધિશાળી', 'વ્યક્તિગત', 'અદ્યતન', 'વ્યાપક', 'સ્માર્ટ'],
    aiHealthAnalysis: 'AI-સંચાલિત આરોગ્ય વિશ્લેષણ',
    uploadDescription: 'તબીબી દસ્તાવેજો અપલોડ કરો અને તાત્કાલિક AI આંતરદૃષ્ટિ મેળવો',
    uploadMedicalRecords: 'તબીબી રેકોર્ડ્સ અપલોડ કરો',
    analysisCompleted: 'વિશ્લેષણ પૂર્ણ',
    analyzing: 'વિશ્લેષણ કરી રહ્યા છીએ...',
    analyzeHealthData: 'આરોગ્ય ડેટાનું વિશ્લેષણ કરો',
    analyzingDocument: 'AI સાથે તમારા તબીબી દસ્તાવેજનું વિશ્લેષણ કરી રહ્યા છીએ...',
    analysisSuccessful: 'વિશ્લેષણ સફળ! તમારો વ્યક્તિગત રિપોર્ટ તૈયાર કરી રહ્યા છીએ...',
    intelligentAssistant: 'બુદ્ધિશાળી આરોગ્ય સહાયક',
    instantAnswers: 'અમારા AI પાસેથી તમારા આરોગ્ય પ્રશ્નોના તાત્કાલિક જવાબો મેળવો',
    listening: 'સાંભળી રહ્યા છીએ...',
    askHealthQuestion: 'આરોગ્ય વિશે કંઈપણ પૂછો...',
    asking: 'પૂછી રહ્યા છીએ...',
    askHealthWellAI: 'હેલ્થવેલ AI ને પૂછો',
    iotHealthMonitoring: 'IoT આરોગ્ય નિરીક્ષણ',
    futurePerk: 'ભવિષ્યનો ફાયદો',
    iotSubtitle: 'વ્યાપક આરોગ્ય વિશ્લેષણ માટે તમારા ઉપકરણો કનેક્ટ કરો અથવા મેન્યુઅલી ડેટા ઇનપુટ કરો',
    comingSoonFeature: 'આ સુવિધા ટૂંક સમયમાં આવી રહી છે! વ્યક્તિગત આરોગ્ય નિરીક્ષણના ભવિષ્યનો અનુભવ કરો।',
    manualInput: 'મેન્યુઅલ ઇનપુટ',
    iotDevices: 'IoT ઉપકરણો',
    heartRate: 'હૃદયના ધબકારા',
    enterBPM: 'BPM દાખલ કરો',
    bloodPressure: 'બ્લડ પ્રેશર',
    systolic: 'સિસ્ટોલિક',
    diastolic: 'ડાયાસ્ટોલિક',
    temperature: 'તાપમાન',
    enterTemp: 'તાપમાન દાખલ કરો',
    oxygenLevel: 'ઓક્સિજન સ્તર',
    enterPercent: '% દાખલ કરો',
    weight: 'વજન',
    enterWeight: 'વજન દાખલ કરો',
    dailySteps: 'દૈનિક પગલાં',
    enterSteps: 'પગલાં દાખલ કરો',
    availableHealthDevices: 'ઉપલબ્ધ આરોગ્ય ઉપકરણો',
    scanning: 'સ્કેન કરી રહ્યા છીએ...',
    scanForDevices: 'ઉપકરણો માટે સ્કેન કરો',
    disconnect: 'ડિસ્કનેક્ટ કરો',
    connect: 'કનેક્ટ કરો',
    generateHealthReport: 'આરોગ્ય રિપોર્ટ જનરેટ કરો',
    healthAnalysisReport: 'તમારો આરોગ્ય વિશ્લેષણ રિપોર્ટ',
    generatedOn: 'જનરેટ કર્યું',
    healthMetricsSummary: 'આરોગ્ય મેટ્રિક્સ સારાંશ',
    sending: 'મોકલી રહ્યા છીએ...',
    send: 'મોકલો',
    advancedHealthcareAnalytics: 'અદ્યતન આરોગ્યસેવા વિશ્લેષણ',
    platform: 'પ્લેટફોર્મ',
    documentAnalysis: 'દસ્તાવેજ વિશ્લેષણ',
    iotIntegration: 'IoT એકીકરણ',
    aiDiagnostics: 'AI નિદાન',
    resources: 'સંસાધનો',
    documentation: 'દસ્તાવેજીકરણ',
    apiReference: 'API સંદર્ભ',
    support: 'સહાય',
    advancedHealthcareTechnology: 'અદ્યતન આરોગ્યસેવા તકનીક',
    hipaaCompliant: 'HIPAA અનુપાલન',
    iso27001: 'ISO 27001',
    fdaApproved: 'FDA મંજૂર',
    signIn: 'સાઇન ઇન',
    getStarted: 'શરૂ કરો',
    copyReport: 'રિપોર્ટ કોપી કરો',
    downloadReport: 'રિપોર્ટ ડાઉનલોડ કરો',
    closeReport: 'રિપોર્ટ બંધ કરો',
    uploadDocument: 'તબીબી દસ્તાવેજ અપલોડ કરો',
    dragDropText: 'તમારા તબીબી દસ્તાવેજો અહીં ખેંચો અને છોડો',
    orText: 'અથવા',
    browseFiles: 'ફાઇલો બ્રાઉઝ કરો',
    supportedFormats: 'સપોર્ટેડ ફોર્મેટ્સ: PDF, JPG, PNG, DOCX',
    analysisComplete: 'વિશ્લેષણ પૂર્ણ!',
    viewReport: 'રિપોર્ટ જુઓ',
    askQuestion: 'આરોગ્ય વિશે કંઈપણ પૂછો...',
    iotTitle: 'IoT આરોગ્ય નિરીક્ષણ',
    scanDevices: 'ઉપકરણો સ્કેન કરો',
    connectDevice: 'ઉપકરણ કનેક્ટ કરો',
    connected: 'કનેક્ટ થયેલ',
    generateReport: 'આરોગ્ય રિપોર્ટ જનરેટ કરો',
    chatTitle: 'આરોગ્ય સહાયક',
    reportTab: 'રિપોર્ટ',
    chatTab: 'ચેટ',
    footerBrand: 'હેલ્થવેલ',
    footerTagline: 'અદ્યતન આરોગ્યસેવા વિશ્લેષણ',
    platformTitle: 'પ્લેટફોર્મ',
    resourcesTitle: 'સંસાધનો',
    copyright: '© 2024 હેલ્થવેલ। અદ્યતન આરોગ્યસેવા તકનીક।',
    home: 'હોમ',
    about: 'વિશે'
  },
  kn: {
    heroTitle: 'ಹೆಲ್ತ್‌ವೆಲ್',
    heroSubtitle: ['ಬುದ್ಧಿವಂತ', 'ವೈಯಕ್ತಿಕ', 'ಸುಧಾರಿತ', 'ಸಮಗ್ರ', 'ಸ್ಮಾರ್ಟ್'],
    aiHealthAnalysis: 'AI-ಚಾಲಿತ ಆರೋಗ್ಯ ವಿಶ್ಲೇಷಣೆ',
    uploadDescription: 'ವೈದ್ಯಕೀಯ ದಾಖಲೆಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಮತ್ತು ತ್ವರಿತ AI ಒಳನೋಟಗಳನ್ನು ಪಡೆಯಿರಿ',
    uploadMedicalRecords: 'ವೈದ್ಯಕೀಯ ದಾಖಲೆಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    analysisCompleted: 'ವಿಶ್ಲೇಷಣೆ ಪೂರ್ಣಗೊಂಡಿದೆ',
    analyzing: 'ವಿಶ್ಲೇಷಿಸುತ್ತಿದ್ದೇವೆ...',
    analyzeHealthData: 'ಆರೋಗ್ಯ ಡೇಟಾವನ್ನು ವಿಶ್ಲೇಷಿಸಿ',
    analyzingDocument: 'AI ಯೊಂದಿಗೆ ನಿಮ್ಮ ವೈದ್ಯಕೀಯ ದಾಖಲೆಯನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತಿದ್ದೇವೆ...',
    analysisSuccessful: 'ವಿಶ್ಲೇಷಣೆ ಯಶಸ್ವಿ! ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ವರದಿಯನ್ನು ತಯಾರಿಸುತ್ತಿದ್ದೇವೆ...',
    intelligentAssistant: 'ಬುದ್ಧಿವಂತ ಆರೋಗ್ಯ ಸಹಾಯಕ',
    instantAnswers: 'ನಮ್ಮ AI ಯಿಂದ ನಿಮ್ಮ ಆರೋಗ್ಯ ಪ್ರಶ್ನೆಗಳಿಗೆ ತ್ವರಿತ ಉತ್ತರಗಳನ್ನು ಪಡೆಯಿರಿ',
    listening: 'ಕೇಳುತ್ತಿದ್ದೇವೆ...',
    askHealthQuestion: 'ಆರೋಗ್ಯದ ಬಗ್ಗೆ ಏನನ್ನಾದರೂ ಕೇಳಿ...',
    asking: 'ಕೇಳುತ್ತಿದ್ದೇವೆ...',
    askHealthWellAI: 'ಹೆಲ್ತ್‌ವೆಲ್ AI ಯನ್ನು ಕೇಳಿ',
    iotHealthMonitoring: 'IoT ಆರೋಗ್ಯ ಮೇಲ್ವಿಚಾರಣೆ',
    futurePerk: 'ಭವಿಷ್ಯದ ಪ್ರಯೋಜನ',
    iotSubtitle: 'ಸಮಗ್ರ ಆರೋಗ್ಯ ವಿಶ್ಲೇಷಣೆಗಾಗಿ ನಿಮ್ಮ ಸಾಧನಗಳನ್ನು ಸಂಪರ್ಕಿಸಿ ಅಥವಾ ಹಸ್ತಚಾಲಿತವಾಗಿ ಡೇಟಾ ಇನ್‌ಪುಟ್ ಮಾಡಿ',
    comingSoonFeature: 'ಈ ವೈಶಿಷ್ಟ್ಯ ಶೀಘ್ರದಲ್ಲೇ ಬರುತ್ತಿದೆ! ವೈಯಕ್ತಿಕ ಆರೋಗ್ಯ ಮೇಲ್ವಿಚಾರಣೆಯ ಭವಿಷ್ಯವನ್ನು ಅನುಭವಿಸಿ.',
    manualInput: 'ಹಸ್ತಚಾಲಿತ ಇನ್‌ಪುಟ್',
    iotDevices: 'IoT ಸಾಧನಗಳು',
    heartRate: 'ಹೃದಯ ಬಡಿತ',
    enterBPM: 'BPM ನಮೂದಿಸಿ',
    bloodPressure: 'ರಕ್ತದೊತ್ತಡ',
    systolic: 'ಸಿಸ್ಟೋಲಿಕ್',
    diastolic: 'ಡಯಾಸ್ಟೋಲಿಕ್',
    temperature: 'ತಾಪಮಾನ',
    enterTemp: 'ತಾಪಮಾನ ನಮೂದಿಸಿ',
    oxygenLevel: 'ಆಮ್ಲಜನಕ ಮಟ್ಟ',
    enterPercent: '% ನಮೂದಿಸಿ',
    weight: 'ತೂಕ',
    enterWeight: 'ತೂಕ ನಮೂದಿಸಿ',
    dailySteps: 'ದೈನಂದಿನ ಹೆಜ್ಜೆಗಳು',
    enterSteps: 'ಹೆಜ್ಜೆಗಳನ್ನು ನಮೂದಿಸಿ',
    availableHealthDevices: 'ಲಭ್ಯವಿರುವ ಆರೋಗ್ಯ ಸಾಧನಗಳು',
    scanning: 'ಸ್ಕ್ಯಾನ್ ಮಾಡುತ್ತಿದ್ದೇವೆ...',
    scanForDevices: 'ಸಾಧನಗಳಿಗಾಗಿ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    disconnect: 'ಸಂಪರ್ಕ ಕಡಿತಗೊಳಿಸಿ',
    connect: 'ಸಂಪರ್ಕಿಸಿ',
    generateHealthReport: 'ಆರೋಗ್ಯ ವರದಿಯನ್ನು ರಚಿಸಿ',
    healthAnalysisReport: 'ನಿಮ್ಮ ಆರೋಗ್ಯ ವಿಶ್ಲೇಷಣೆ ವರದಿ',
    generatedOn: 'ರಚಿಸಲಾಗಿದೆ',
    healthMetricsSummary: 'ಆರೋಗ್ಯ ಮೆಟ್ರಿಕ್ಸ್ ಸಾರಾಂಶ',
    sending: 'ಕಳುಹಿಸುತ್ತಿದ್ದೇವೆ...',
    send: 'ಕಳುಹಿಸಿ',
    advancedHealthcareAnalytics: 'ಸುಧಾರಿತ ಆರೋಗ್ಯ ಸೇವಾ ವಿಶ್ಲೇಷಣೆ',
    platform: 'ವೇದಿಕೆ',
    documentAnalysis: 'ದಾಖಲೆ ವಿಶ್ಲೇಷಣೆ',
    iotIntegration: 'IoT ಏಕೀಕರಣ',
    aiDiagnostics: 'AI ರೋಗನಿರ್ಣಯ',
    resources: 'ಸಂಪನ್ಮೂಲಗಳು',
    documentation: 'ದಾಖಲೀಕರಣ',
    apiReference: 'API ಉಲ್ಲೇಖ',
    support: 'ಬೆಂಬಲ',
    advancedHealthcareTechnology: 'ಸುಧಾರಿತ ಆರೋಗ್ಯ ಸೇವಾ ತಂತ್ರಜ್ಞಾನ',
    hipaaCompliant: 'HIPAA ಅನುಸರಣೆ',
    iso27001: 'ISO 27001',
    fdaApproved: 'FDA ಅನುಮೋದಿತ',
    signIn: 'ಸೈನ್ ಇನ್',
    getStarted: 'ಪ್ರಾರಂಭಿಸಿ',
    copyReport: 'ವರದಿಯನ್ನು ನಕಲಿಸಿ',
    downloadReport: 'ವರದಿಯನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    closeReport: 'ವರದಿಯನ್ನು ಮುಚ್ಚಿ',
    uploadDocument: 'ವೈದ್ಯಕೀಯ ದಾಖಲೆಯನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    dragDropText: 'ನಿಮ್ಮ ವೈದ್ಯಕೀಯ ದಾಖಲೆಗಳನ್ನು ಇಲ್ಲಿ ಎಳೆದು ಬಿಡಿ',
    orText: 'ಅಥವಾ',
    browseFiles: 'ಫೈಲ್‌ಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ',
    supportedFormats: 'ಬೆಂಬಲಿತ ಸ್ವರೂಪಗಳು: PDF, JPG, PNG, DOCX',
    analysisComplete: 'ವಿಶ್ಲೇಷಣೆ ಪೂರ್ಣಗೊಂಡಿದೆ!',
    viewReport: 'ವರದಿಯನ್ನು ವೀಕ್ಷಿಸಿ',
    askQuestion: 'ಆರೋಗ್ಯದ ಬಗ್ಗೆ ಏನನ್ನಾದರೂ ಕೇಳಿ...',
    iotTitle: 'IoT ಆರೋಗ್ಯ ಮೇಲ್ವಿಚಾರಣೆ',
    scanDevices: 'ಸಾಧನಗಳನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    connectDevice: 'ಸಾಧನವನ್ನು ಸಂಪರ್ಕಿಸಿ',
    connected: 'ಸಂಪರ್ಕಿಸಲಾಗಿದೆ',
    generateReport: 'ಆರೋಗ್ಯ ವರದಿಯನ್ನು ರಚಿಸಿ',
    chatTitle: 'ಆರೋಗ್ಯ ಸಹಾಯಕ',
    reportTab: 'ವರದಿ',
    chatTab: 'ಚಾಟ್',
    footerBrand: 'ಹೆಲ್ತ್‌ವೆಲ್',
    footerTagline: 'ಸುಧಾರಿತ ಆರೋಗ್ಯ ಸೇವಾ ವಿಶ್ಲೇಷಣೆ',
    platformTitle: 'ವೇದಿಕೆ',
    resourcesTitle: 'ಸಂಪನ್ಮೂಲಗಳು',
    copyright: '© 2024 ಹೆಲ್ತ್‌ವೆಲ್। ಸುಧಾರಿತ ಆರೋಗ್ಯ ಸೇವಾ ತಂತ್ರಜ್ಞಾನ।',
    home: 'ಮುಖಪುಟ',
    about: 'ಬಗ್ಗೆ'
  },
  ml: {
    heroTitle: 'ഹെൽത്ത്‌വെൽ',
    heroSubtitle: ['ബുദ്ധിമാൻ', 'വ്യക്തിഗത', 'വിപുലമായ', 'സമഗ്ര', 'സ്മാർട്ട്'],
    aiHealthAnalysis: 'AI-പവർഡ് ആരോഗ്യ വിശകലനം',
    uploadDescription: 'മെഡിക്കൽ ഡോക്യുമെന്റുകൾ അപ്‌ലോഡ് ചെയ്ത് തൽക്ഷണ AI ഇൻസൈറ്റുകൾ നേടുക',
    uploadMedicalRecords: 'മെഡിക്കൽ റെക്കോർഡുകൾ അപ്‌ലോഡ് ചെയ്യുക',
    analysisCompleted: 'വിശകലനം പൂർത്തിയായി',
    analyzing: 'വിശകലനം ചെയ്യുന്നു...',
    analyzeHealthData: 'ആരോഗ്യ ഡാറ്റ വിശകലനം ചെയ്യുക',
    analyzingDocument: 'AI ഉപയോഗിച്ച് നിങ്ങളുടെ മെഡിക്കൽ ഡോക്യുമെന്റ് വിശകലനം ചെയ്യുന്നു...',
    analysisSuccessful: 'വിശകലനം വിജയകരം! നിങ്ങളുടെ വ്യക്തിഗത റിപ്പോർട്ട് തയ്യാറാക്കുന്നു...',
    intelligentAssistant: 'ബുദ്ധിമാനായ ആരോഗ്യ സഹായി',
    instantAnswers: 'ഞങ്ങളുടെ AI-യിൽ നിന്ന് നിങ്ങളുടെ ആരോഗ്യ ചോദ്യങ്ങൾക്ക് തൽക്ഷണ ഉത്തരങ്ങൾ നേടുക',
    listening: 'കേൾക്കുന്നു...',
    askHealthQuestion: 'ആരോഗ്യത്തെക്കുറിച്ച് എന്തും ചോദിക്കുക...',
    asking: 'ചോദിക്കുന്നു...',
    askHealthWellAI: 'ഹെൽത്ത്‌വെൽ AI-യോട് ചോദിക്കുക',
    iotHealthMonitoring: 'IoT ആരോഗ്യ നിരീക്ഷണം',
    futurePerk: 'ഭാവി ആനുകൂല്യം',
    iotSubtitle: 'സമഗ്ര ആരോഗ്യ വിശകലനത്തിനായി നിങ്ങളുടെ ഉപകരണങ്ങൾ കണക്റ്റ് ചെയ്യുക അല്ലെങ്കിൽ സ്വമേധയാ ഡാറ്റ ഇൻപുട്ട് ചെയ്യുക',
    comingSoonFeature: 'ഈ ഫീച്ചർ ഉടൻ വരുന്നു! വ്യക്തിഗത ആരോഗ്യ നിരീക്ഷണത്തിന്റെ ഭാവി അനുഭവിക്കുക.',
    manualInput: 'മാനുവൽ ഇൻപുട്ട്',
    iotDevices: 'IoT ഉപകരണങ്ങൾ',
    heartRate: 'ഹൃദയമിടിപ്പ്',
    enterBPM: 'BPM നൽകുക',
    bloodPressure: 'രക്തസമ്മർദ്ദം',
    systolic: 'സിസ്റ്റോളിക്',
    diastolic: 'ഡയാസ്റ്റോളിക്',
    temperature: 'താപനില',
    enterTemp: 'താപനില നൽകുക',
    oxygenLevel: 'ഓക്സിജൻ നില',
    enterPercent: '% നൽകുക',
    weight: 'ഭാരം',
    enterWeight: 'ഭാരം നൽകുക',
    dailySteps: 'ദൈനംദിന ചുവടുകൾ',
    enterSteps: 'ചുവടുകൾ നൽകുക',
    availableHealthDevices: 'ലഭ്യമായ ആരോഗ്യ ഉപകരണങ്ങൾ',
    scanning: 'സ്കാൻ ചെയ്യുന്നു...',
    scanForDevices: 'ഉപകരണങ്ങൾക്കായി സ്കാൻ ചെയ്യുക',
    disconnect: 'വിച്ഛേദിക്കുക',
    connect: 'കണക്റ്റ് ചെയ്യുക',
    generateHealthReport: 'ആരോഗ്യ റിപ്പോർട്ട് സൃഷ്ടിക്കുക',
    healthAnalysisReport: 'നിങ്ങളുടെ ആരോഗ്യ വിശകലന റിപ്പോർട്ട്',
    generatedOn: 'സൃഷ്ടിച്ചത്',
    healthMetricsSummary: 'ആരോഗ്യ മെട്രിക്സ് സംഗ്രഹം',
    sending: 'അയയ്ക്കുന്നു...',
    send: 'അയയ്ക്കുക',
    advancedHealthcareAnalytics: 'വിപുലമായ ആരോഗ്യസേവന വിശകലനം',
    platform: 'പ്ലാറ്റ്ഫോം',
    documentAnalysis: 'ഡോക്യുമെന്റ് വിശകലനം',
    iotIntegration: 'IoT സംയോജനം',
    aiDiagnostics: 'AI രോഗനിർണയം',
    resources: 'വിഭവങ്ങൾ',
    documentation: 'ഡോക്യുമെന്റേഷൻ',
    apiReference: 'API റഫറൻസ്',
    support: 'പിന്തുണ',
    advancedHealthcareTechnology: 'വിപുലമായ ആരോഗ്യസേവന സാങ്കേതികവിദ്യ',
    hipaaCompliant: 'HIPAA അനുസരണം',
    iso27001: 'ISO 27001',
    fdaApproved: 'FDA അംഗീകൃതം',
    signIn: 'സൈൻ ഇൻ',
    getStarted: 'ആരംഭിക്കുക',
    copyReport: 'റിപ്പോർട്ട് പകർത്തുക',
    downloadReport: 'റിപ്പോർട്ട് ഡൗൺലോഡ് ചെയ്യുക',
    closeReport: 'റിപ്പോർട്ട് അടയ്ക്കുക',
    uploadDocument: 'മെഡിക്കൽ ഡോക്യുമെന്റ് അപ്‌ലോഡ് ചെയ്യുക',
    dragDropText: 'നിങ്ങളുടെ മെഡിക്കൽ ഡോക്യുമെന്റുകൾ ഇവിടെ വലിച്ചിട്ടുക',
    orText: 'അല്ലെങ്കിൽ',
    browseFiles: 'ഫയലുകൾ ബ്രൗസ് ചെയ്യുക',
    supportedFormats: 'പിന്തുണയ്ക്കുന്ന ഫോർമാറ്റുകൾ: PDF, JPG, PNG, DOCX',
    analysisComplete: 'വിശകലനം പൂർത്തിയായി!',
    viewReport: 'റിപ്പോർട്ട് കാണുക',
    askQuestion: 'ആരോഗ്യത്തെക്കുറിച്ച് എന്തും ചോദിക്കുക...',
    iotTitle: 'IoT ആരോഗ്യ നിരീക്ഷണം',
    scanDevices: 'ഉപകരണങ്ങൾ സ്കാൻ ചെയ്യുക',
    connectDevice: 'ഉപകരണം കണക്റ്റ് ചെയ്യുക',
    connected: 'കണക്റ്റ് ചെയ്തു',
    generateReport: 'ആരോഗ്യ റിപ്പോർട്ട് സൃഷ്ടിക്കുക',
    chatTitle: 'ആരോഗ്യ സഹായി',
    reportTab: 'റിപ്പോർട്ട്',
    chatTab: 'ചാറ്റ്',
    footerBrand: 'ഹെൽത്ത്‌വെൽ',
    footerTagline: 'വിപുലമായ ആരോഗ്യസേവന വിശകലനം',
    platformTitle: 'പ്ലാറ്റ്ഫോം',
    resourcesTitle: 'വിഭവങ്ങൾ',
    copyright: '© 2024 ഹെൽത്ത്‌വെൽ। വിപുലമായ ആരോഗ്യസേവന സാങ്കേതികവിദ്യ।',
    home: 'ഹോം',
    about: 'കുറിച്ച്'
  }
};

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState(() => {
    // Check localStorage first, then default to English
    const savedLanguage = localStorage.getItem('healthwell-language');
    return savedLanguage || 'en';
  });

  useEffect(() => {
    // Save to localStorage whenever language changes
    localStorage.setItem('healthwell-language', currentLanguage);
    
    // Update document language attribute
    document.documentElement.lang = currentLanguage;
  }, [currentLanguage]);

  const changeLanguage = (languageCode) => {
    if (translations[languageCode]) {
      setCurrentLanguage(languageCode);
    }
  };

  const t = (key) => {
    return translations[currentLanguage]?.[key] || translations.en[key] || key;
  };

  const value = {
    currentLanguage,
    changeLanguage,
    t,
    availableLanguages: Object.keys(translations)
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};